version: '3.8'

services:
  caddy_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"

  node_app:
    build:
      context: .
      dockerfile: todo_back/Dockerfile
    container_name: node_app
    expose:
      - "4001"
      - "4002"
      - "4003"
  mysql_server:
    build:
      context: .
      dockerfile: todo_back/mysql/Dockerfile
    container_name: mysql_server
    expose:
      - "3306"
